### ISSUE TITLE
FEATURE: theme support

### ISSUE THREAD

**Issue by nwhitehead** [nwhitehead/pineapple#10]
Work on some fun color/font themes, add menu item to select between themes. Makes better screenshots to entice people.

**Comment by nwhitehead** [comment]
Dynamic theme loading implemented in js, themes split out. Light theme is loaded at page load, can be swapped with a simple js command.

Remaining work: figure out how the main app should choose which theme to invoke. Make preference persistent, add a menu item to switch it. Add some other cool themes.

**Comment by nwhitehead** [comment]
I'm calling this done. There is a menu with theme choices, preference of theme is persistent in preferences, and the themes are mostly usable.

**Comment by jonrobinson2** [comment]
Themes don't seem to be working on my version of Pineapple Pro. Any ideas on why it wouldn't?

**Comment by N2ITN** [comment]
Is there a way to change themes from a compiled version? I have a hard time reading the included font.
