### ISSUE TITLE
there appears to be a problem connecting to the local computation server

### ISSUE THREAD

**Issue by duobei** [nwhitehead/pineapple#13]
![1 pic_hd](https://cloud.githubusercontent.com/assets/926853/9707969/b019e888-5547-11e5-873a-086340ca00a8.jpg)

And I have runned the iPython notebook local.

![2 pic_hd](https://cloud.githubusercontent.com/assets/926853/9707989/05fe8312-5548-11e5-892d-2c59ab47c27f.jpg)

Are there docs about how to use pineapple?

**Comment by nwhitehead** [comment]
Hi Peter,

The basic idea is that you should be able to start Pineapple and it just
shows up a notebook with nothing else required. One problem is if you are
already running a server on port 8888, then Pineapple will try to use that
port and fail. I'm working on a fix to make Pineapple choose a different
port. For now, you need to turn off any servers on 8888 (including any
other instances of IPython/Jupyter). Then run Pineapple and hopefully it
should work.

If it still doesn't work, you can try going into Terminal and typing:

/Applications/Pineapple.app/Contents/MacOS/Pineapple

That will run it and let you see debugging messages as it tries to start.

Best,

--

Nathan

**Comment by duobei** [comment]
@nwhitehead Thanks. It works.

**Comment by nwhitehead** [comment]
Awesome, good to hear it!
