### ISSUE TITLE
No response when access submenus

### ISSUE THREAD

**Issue by xiaoweiz** [nwhitehead/pineapple#21]
The items with more options in the dropdown menu do not seem work. For instance, in the following screenshot, I can use Down Arrow to navigate to "cell type" and then it's kind of "forzen" there. I can't expand more options using Right Arrow or Return. I can't move further down to "Current Output" using Down Arrow, either. 
![screen shot 2015-09-17 at 9 33 50 am](https://cloud.githubusercontent.com/assets/4540215/9922794/3c1c650c-5d1f-11e5-9197-0a4b8fb0d4ef.png)

If I use mouse to click "Cell Type", the submenu will pop up and vanish immediately. There's even no time for a screenshot. 

I first noticed the behaviour with Pineapple 0.6 and the recent 0.7 doesn't fix it. The issue has been replicated on at least two Mac machines with Yosemite OSX.

**Comment by nwhitehead** [comment]
That doesn't look right, the header, menu, and toolbar should be disabled inside the page. The intention is that you use the Mac menubar and the toolbar in the window itself (the colorful one).

If you are using a prebuilt release let me know so I can fix it.

If you are building from source then I think I know the issue. You need to do a "make install-custom" step to copy the custom.css and theme files into the right area. The cmake file is not great about doing all the correct dependencies automatically.

**Comment by xiaoweiz** [comment]
I was using the prebuilt release.

**Comment by nwhitehead** [comment]
Do you get the header/menubar/toolbar in all the released 0.7.4 versions?

**Comment by xiaoweiz** [comment]
Right, all the four variants.

**Comment by nwhitehead** [comment]
Could you run this in a cell and let me know what you get:

import sys
print(sys.version)
print(sys.path)

**Comment by xiaoweiz** [comment]
<img width="968" alt="screen shot 2015-09-18 at 1 24 34 am" src="https://cloud.githubusercontent.com/assets/4540215/9940726/1353b58c-5da4-11e5-864d-8e3c48672b45.png">

**Comment by nwhitehead** [comment]
That's weird, I'm not sure how it is getting the anaconda version of Python. I need to look into that more.

One thing to try is to backup and then delete all your local IPython/Jupyter configuration files. This is directories like ~/Library/Jupyter, ~/.jupyter, ~/.ipython.

**Comment by xiaoweiz** [comment]
Removing these folders solves the problem!

**Comment by mangecoeur** [comment]
Just to say I also have this issue,  though I'm not willing to delete my local config files though since i need the regular ipython for work to see if it changes things...

**Comment by nwhitehead** [comment]
With the latest changes, Pineapple uses different configuration directories than any previous install of Jupyter/IPython. If you see the same problems in later releases go ahead and reopen this issue or file a new one.
