### ISSUE TITLE
Ping from ipython-desktop

### ISSUE THREAD

**Issue by mangecoeur** [nwhitehead/pineapple#22]
Hi, really impressive project! I have worked on something similar - ipython deskop:  https://github.com/mangecoeur/ipython-desktop which I put on hold pending the Jupyter update/split.

I'm really keen to see some kind of desktop frontend emerge for ipython, though I'm personally short on time I'd like to contribute (though I see you went down the native/C route which isn't my strong point :P )

**Comment by nwhitehead** [comment]
Very cool, I hadn't seen that before. Let me know if you have any ideas or
suggestions for Pineapple.

The C++ application part of it is actually not too bad, it's mostly
wxwidgets. Most of the complexity is in the final packaging to make sure
everything actually works (dynamic libraries, paths, etc.)

**Comment by mangecoeur** [comment]
Yeah I've been looking through the project, the wx code doesn't look too hairy (normally I'm instantly put off C++ codebases, yours is very neat). What would be really cool is if you could document the build/packaging process (e.g. in the wiki or a blog post) - i think this is something a lot of people struggle with, whether for this kind of project or others, if you could capture that knowledge it might save a lot of people a lot of trouble!
