### ISSUE TITLE
FEATURE: Use Javascript (or any other) kernel in Pineapple

### ISSUE THREAD

**Issue by gnestor** [nwhitehead/pineapple#27]
I'm not sure if this is possible already but I don't see any documentation about it...

**Comment by nwhitehead** [comment]
Not possible yet but the ability to use other kernels is a high priority.
Including other kernels inside the app is on the roadmap but is lower
priority.

**Comment by gnestor** [comment]
Look forward to using Javascript/Node.js in Pineapple. Great work so far!

**Comment by gnestor** [comment]
Merging with this one: https://github.com/nwhitehead/pineapple/issues/23

**Comment by RobertTalbert** [comment]
I would greatly love to be able use the Haskell kernel with Pineapple. Glad to hear this issue is a high priority.
