### ISSUE TITLE
Any chance of including seaborn? 

### ISSUE THREAD

**Issue by desilinguist** [nwhitehead/pineapple#28]
This app has the potential to transform my workflow! Amazing! Any chance you could include [seaborn](http://stanford.edu/~mwaskom/software/seaborn/) in the main distribution? It's what I use everyday.

**Comment by nwhitehead** [comment]
I'll give it a try and include it in the full version if it works.

**Comment by nwhitehead** [comment]
Included in extra packages, will be available next release.

**Comment by desilinguist** [comment]
Excellent! Thanks.

**Comment by m-macaskill** [comment]
Perhaps similar to report #28, have found that "import seaborn" yields this error (Pineapple-0.8.0 2015-10-11T14:25:44):


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-085c0287ecb5> in <module>()
----> 1 import seaborn

/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/seaborn/__init__.py in <module>()
----> 1 from .rcmod import *
      2 from .utils import *
      3 from .palettes import *
      4 from .linearmodels import *
      5 from .categorical import *

/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/seaborn/rcmod.py in <module>()
      3 import matplotlib as mpl
      4 
----> 5 from . import palettes
      6 
      7 

/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/seaborn/palettes.py in <module>()
     12 from .external.six.moves import range
     13 
---> 14 from .utils import desaturate, set_hls_values
     15 from .xkcd_rgb import xkcd_rgb
     16 from .crayons import crayons

/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/seaborn/utils.py in <module>()
      6 
      7 import numpy as np
----> 8 from scipy import stats
      9 import pandas as pd
     10 import matplotlib.colors as mplcol

/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/stats/__init__.py in <module>()
    319 from __future__ import division, print_function, absolute_import
    320 
--> 321 from .stats import *
    322 from .distributions import *
    323 from .morestats import *

/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/stats/stats.py in <module>()
    178 from scipy._lib.six import callable, string_types
    179 from numpy import array, asarray, ma, zeros
--> 180 import scipy.special as special
    181 import scipy.linalg as linalg
    182 import numpy as np

/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/special/__init__.py in <module>()
    599 from __future__ import division, print_function, absolute_import
    600 
--> 601 from ._ufuncs import *
    602 
    603 from .basic import *

ImportError: dlopen(/Applications/Pineapple.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/Cellar/gcc/5.2.0/lib/gcc/5/libquadmath.0.dylib
  Referenced from: /Applications/Pineapple.app/Contents/Frameworks/libgfortran.3.dylib
  Reason: image not found
