### ISSUE TITLE
Make toolbar less massive

### ISSUE THREAD

**Issue by sammcj** [nwhitehead/pineapple#31]
The toolbar in Pineapple is massive and uses a lot of screen realestate and there doesn't seem to be any option to use smaller icons.

It would be nice if this could be reduced in size significantly.

![screen shot 2015-09-18 at 5 03 28 pm](https://cloud.githubusercontent.com/assets/862951/9953813/788ba6e8-5e27-11e5-9784-f131294e1bec.jpg)

**Comment by mangecoeur** [comment]
I agree - The space taken up by the toolbar is actually the same as that taken up by the firefox UI when I just run in browser. I would add 3 options:

1. Small Icons on/off (about half the size)
2. text-under-icons on/off (you see this option a lot in OSX apps, take Cyberduck as an example)
3. show/hide the entire toolbar (most of the functionality is replicated in the menubar, so if you wanted you could get by entirely without it)

**Comment by scottstanfield** [comment]
+1

**Comment by nwhitehead** [comment]
The masses have spoken!

Done, there are now configuration options to hide the toolbar, turn the text on and off, and set the icon size. There are menu options under "View" for no toolbar, small toolbar without text, and the standard big one.

**Comment by sammcj** [comment]
Now that was some quick turnaround!

Thanks so much :+1:
