### ISSUE TITLE
Importing scipy.signal fails

### ISSUE THREAD

**Issue by m-macaskill** [nwhitehead/pineapple#35]
`import scipy` works but not `import scipy.signal` or `from scipy import signal`. The error message below occurs. Does this indicate the need for some dependency that isn't contained within the Pineapple installation itself?

ImportError                               Traceback (most recent call last)
<ipython-input-3-c14ca79fb68c> in <module>()
----> 1 from scipy import signal

/Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/signal/__init__.py in <module>()
    278 from .spline import *
    279 
--> 280 from .bsplines import *
    281 from .cont2discrete import *
    282 from .dltisys import *

/Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/signal/bsplines.py in <module>()
     10 from .spline import cspline2d, sepfir2d
     11 
---> 12 from scipy.special import comb, gamma
     13 
     14 __all__ = ['spline_filter', 'bspline', 'gauss_spline', 'cubic', 'quadratic',

/Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/special/__init__.py in <module>()
    599 from __future__ import division, print_function, absolute_import
    600 
--> 601 from ._ufuncs import *
    602 
    603 from .basic import *

ImportError: dlopen(/Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-darwin.so
  Reason: image not found

**Comment by nwhitehead** [comment]
Right now Pineapple is not including gfortran libraries, looks like it needs to.

One workaround for the current version is to run "brew install gcc" to get gfortran installed into /usr/local/lib.

**Comment by nwhitehead** [comment]
Recent changes should fix this for the next release. Leave a comment if you still see problems after the next release.

**Comment by m-macaskill** [comment]
Same problem still present for me, using Pineapple-0.8.0
(2015-10-11T14:25:44).

**Comment by MrSage** [comment]
Seeing this still in Pineapple-0.8.0
