### ISSUE TITLE
“Pineapple” is damaged and can’t be opened. You should move it to the Trash. -- OS X 10.11.1

### ISSUE THREAD

**Issue by marksimi** [nwhitehead/pineapple#51]
python 2.7 on OS X 10.11.1

**Comment by cdiazbas** [comment]
I had the same problem (python 2.7 on OSX 10.11.2). The solution in other issue: https://github.com/nwhitehead/pineapple/issues/48. Write in the terminal: 

install_name_tool -change /usr/local/lib/libwx_osx_cocoau-3.1.dylib @executable_path/libwx_osx_cocoau-3.1.dylib /Applications/Pineapple.app/Contents/MacOS/Pineapple

**Comment by marksimi** [comment]
@cdiazbas missed your response; this worked!  thanks for the assist :)
