### ISSUE TITLE
changing theme not functioning

### ISSUE THREAD

**Issue by laurentperrinet** [nwhitehead/pineapple#52]
thanks for this amazing package - truly great to bring new people to the world of jupyter!

on a fresh install, I tried to change the theme of a notebook - this effectively changed the value in `~/Library/Application Support/Pineapple/preferences` - however, nothing changed in the rendering.

cheers,
Laurent

**Comment by RMKD** [comment]
I have the same issue (OSX 10.11.3)

**Comment by laurentperrinet** [comment]
I am using nteract - thanks!
