### ISSUE TITLE
Import modules

### ISSUE THREAD

**Issue by soobrosa** [nwhitehead/pineapple#62]
Hi,

tried to import not burnt in modules in 0.7.4. failed.

Tried latest 0.8.0 P2.7 - it doesn't even start throwing a EXC_BREAKPOINT (SIGTRAP).

Do you maybe have an idea how to mitigate?

Cheers,
Daniel

**Comment by pog87** [comment]
have yoy tried this?
```python
import pip
pip.main(['install', "burnt"])
```

**Comment by soobrosa** [comment]
thanks for the hacky tip it drops
```

  File "/Applications/Pineapple-Pro.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/db/__init__.py", line 69
    print "var", var
              ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by kevinr** [comment]
I ran into this while Googling for the same issue, and later found from [data/examples/python2.7/Packages.ipynb](https://github.com/nwhitehead/pineapple/blob/486b1c87357e1e40766a0d3496c9a3be1f50500f/data/examples/python2.7/Packages.ipynb) that it looks like

```
import pineapple
%pip install burnt
```

is the right way to do this.

**Comment by soobrosa** [comment]
Thanks, Pineapple does not even start since then.
